---
- name: Setup Apache web server and create sample page
  hosts: all
  become: true

  tasks:
    - name: Create facts.txt file with Ansible managed node IP
      blockinfile:
        path: /root/facts.txt
        content: |
          Ansible managed node IP is {{ ansible_default_ipv4.address }}
        create: true
        marker: ""

    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Copy facts.txt to index.html
      copy:
        src: /root/facts.txt
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: "0644"
        remote_src: true

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
