apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
data:
  username: dXNlcm5hbWU=   # Valor codificado en base64: "username"
  password: cGFzc3dvcmQ=   # Valor codificado en base64: "password"
  # Agrega aquí los datos codificados en base64 de tus Secrets
