apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-script-job
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        command: ["sh", "-c", "mysql -h mysql-service -u root -p$MYSQL_ROOT_PASSWORD < /scripts/script.sql"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: script-configmap
  backoffLimit: 4
